const ebookEditions = [
  {
    id: 'verde',
    name: 'Detox Verde',
    badge: 'VOLUME 1',
    headline: 'ELIMINE TOXINAS<br>E PERCA ATÉ 5KG<br><em>EM 7 DIAS</em>',
    description: 'Smoothies verdes, sucos detox e bowls nutritivos com ingredientes que desintoxicam e energizam.',
    benefits: ['+30 receitas exclusivas', 'Lista de compras', 'Plano 7 dias'],
    colors: {
      bgPrimary: '#D4EDDA',
      bgGradient: '#A8D5A2',
      accent: '#2E7D32',
      textHero: '#1B5E20',
      badge: '#66BB6A',
    },
    bottleColor: '#43A047',
    bottleImg: 'assets/images/bottles/detoxverde.webp',
    fruits: [
      { src: 'assets/images/fruits/kiwi.webp', x: 10, bottom: 10, size: 140 },
      { src: 'assets/images/fruits/limao.webp', right: 10, top: 12, size: 130 },
    ],
  },
  {
    id: 'vermelho',
    name: 'Detox Vermelho',
    badge: 'VOLUME 2',
    headline: 'PELE RADIANTE<br>E CORPO LIVRE<br><em>DE INCHAÇO</em>',
    description: 'Vitaminas antioxidantes, chás termogênicos e refeições leves para proteger e revitalizar.',
    benefits: ['+20 receitas funcionais', 'Cardápio semanal', 'Dicas nutricionais'],
    colors: {
      bgPrimary: '#FFEBEE',
      bgGradient: '#EF9A9A',
      accent: '#C62828',
      textHero: '#B71C1C',
      badge: '#EF5350',
    },
    bottleColor: '#E53935',
    bottleImg: 'assets/images/bottles/detoxvermelho.webp',
    fruits: [
      { src: 'assets/images/fruits/morango.webp', right: 10, top: 10, size: 160 },
      { src: 'assets/images/fruits/roma.webp', x: 10, bottom: 10, size: 140 },
    ],
  },
  {
    id: 'laranja',
    name: 'Detox Laranja',
    badge: 'VOLUME 3',
    headline: 'ACELERE SEU<br>METABOLISMO E<br><em>QUEIME GORDURA</em>',
    description: 'Sucos dourados, cremes e saladas com cúrcuma e cenoura para uma pele radiante de dentro para fora.',
    benefits: ['+15 receitas beauty', 'Guia de ingredientes', 'Rotina matinal'],
    colors: {
      bgPrimary: '#FFF3E0',
      bgGradient: '#FFCC80',
      accent: '#E65100',
      textHero: '#BF360C',
      badge: '#FF7043',
    },
    bottleColor: '#FF6D00',
    bottleImg: 'assets/images/bottles/detoxlaranja.webp',
    fruits: [
      { src: 'assets/images/fruits/laranja.webp', right: 10, top: 15, size: 150 },
      { src: 'assets/images/fruits/cenoura.webp', x: 8, bottom: 8, size: 140 },
    ],
  },
];
